model_name: /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-Coder-7B-Instruct/snapshots/c03e6d358207e414f1eca0bb1891e29f1db0e242
model_path: /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-Coder-7B-Instruct/snapshots/c03e6d358207e414f1eca0bb1891e29f1db0e242
tensor_parallel_size: 1
moe_expert_parallel_size: 1
enable_attention_dp: false
max_num_tokens: 32768
max_batch_size: 256
trust_remote_code: false
backend: pytorch
enable_chunked_prefill: false
dtype: bfloat16
kv_cache_config:
  free_gpu_memory_fraction: 0.90
use_cuda_graph: true

